trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel ninja-build meson
  displayName: 'setup'
- script: |
    which meson
    meson --version
    meson builddir
    cd builddir
    ninja
  displayName: 'meson'

