trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build
    sudo apt-get install meson
  displayName: 'setup'
- script: |
    which meson
    meson build
    cd build
    ninja
  displayName: 'meson'

