trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install python3 python3-pip python3-setuptools \
                       python3-wheel ninja-build
    pip3 install --user meson
    export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE);')/bin"
    meson build
    cd build
    ninja
  displayName: 'meson'
